server:
  port: 8183
  error:
    include-message: always
    include-binding-errors: always
  
spring:
  application:
    name: SalesService

  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: eventpro
    hibernate:
      ddl-auto: update
      format_sql: true
      show_sql: false
      properties:
        hibernate:
          highlight_sql: true
          format_sql: true
          jdbc:
            lob:
              non_contextual_creation: true
          type:
            trace: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: sales-group

  security:
    oauth2:
      client:
        registration:
          sales-client:
            authorization-grant-type: client_credentials
            client-id: sales-client
            client-secret: KMXnuhk0wvZhhagau4lESnMzC4S2EgNn
            scope: openid
            provider: sales-provider
            token-uri: http://keycloak:8080/realms/master/protocol/openid-connect/token
        provider:
          sales-provider:
            authorization-uri: http://keycloak:8080/realms/master/protocol/openid-connect/auth
            token-uri: http://keycloak:8080/realms/master/protocol/openid-connect/token
            user-info-uri: https://keycloak:8080/auth/realms/master/protocol/openid-connect/userinfo
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/master/protocol/openid-connect/certs

kafka:
  topic:
    ticket:
      sale:
        created: ticket.sale.created
        done: ticket.sale.done
    payment:
      success: payment.success
      fail: payment.fail
